### ISSUE TITLE
Reset?

### ISSUE THREAD

**Issue by andyle9191** [sparkfun/SparkFun_STUSB4500_Arduino_Library#1]
In the datasheet of the STUSB4500 I see mentions of a reset function, but I do not see one in the library. 
To my understanding, this function will force a renegotiation with the charger.
In my testing, I see this as a very useful function. When I upload new PDO settings, voltages will not change until the module is reset.

**Comment by awende** [comment]
Added soft reset function as well as example4 to demonstrate how to use it with the latest release (V1.1.0).
